import assert from 'node:assert/strict';
import { TOPICS, LETTERS, makeRoom, apply, view, expire, totalFor, makeCode } from '../lib/game.mjs';
const s=makeRoom('123456','host','Házigazda','private-host');
s.players.push({id:'guest',name:'Vendég',hash:'private-guest',removed:false});
const host=s.players[0], guest=s.players[1];
for(let i=0;i<2000;i++)assert.match(makeCode(),/^\d{6}$/);
assert.equal(TOPICS.length,14);
assert.throws(()=>apply(s,guest,'start'),/házigazda/);
apply(s,host,'start');
assert.equal(s.rounds[0].topics.length,7);assert.equal(new Set(s.rounds[0].topics).size,7);
let r=s.rounds.at(-1);r.letter='A';
apply(s,host,'answers',{roundId:r.id,answers:['Alma','Alfa','','Béla','Ár','A saját','A hatodik']});
apply(s,guest,'answers',{roundId:r.id,answers:['aLMA','A másik','','','Ar','A vendég','']});
const concealed=view(s,guest);assert.equal(concealed.round.players[0].answers,undefined);assert.equal(JSON.stringify(concealed).includes('private-host'),false);
apply(s,host,'submit',{roundId:r.id,answers:r.players[0].answers});
assert.throws(()=>apply(s,host,'answers',{roundId:r.id,answers:Array(7).fill('Alma')}),/beküldted/);
apply(s,guest,'submit',{roundId:r.id,answers:r.players[1].answers});
assert.equal(s.phase,'review');assert.deepEqual(r.players[0].points,[0,1,0,0,0,1,1]);assert.deepEqual(r.players[1].points,[0,1,0,0,0,1,0]);
assert.throws(()=>apply(s,guest,'score',{roundId:r.id,playerId:'guest',value:80}),/házigazda/);
apply(s,host,'score',{roundId:r.id,playerId:'guest',value:23});assert.equal(totalFor(s,'guest'),23);
apply(s,host,'score',{roundId:r.id,playerId:'guest',index:0,value:4});assert.equal(totalFor(s,'guest'),27);
apply(s,host,'kick',{playerId:'guest'});assert.equal(guest.removed,true);
apply(s,host,'start');assert.equal(s.rounds.at(-1).players.length,1);
assert.throws(()=>apply(s,host,'answers',{roundId:r.id,answers:Array(7).fill('')}),/lezárult/);
assert.equal(expire(s,s.rounds.at(-1).deadline+1),true);assert.equal(s.phase,'review');
const deck=makeRoom('222222','h','H','x');for(let i=0;i<LETTERS.length;i++){apply(deck,deck.players[0],'start');apply(deck,deck.players[0],'stop',{roundId:deck.rounds.at(-1).id});}assert.equal(new Set(deck.rounds.map(r=>r.letter)).size,LETTERS.length);apply(deck,deck.players[0],'start');assert.equal(deck.usedLetters.length,1);
console.log('PASS: 6-digit codes; 7 distinct topics; nonrepeating letter deck; hidden answers; 1/0 case-insensitive scoring; locked submissions; host permissions; score edits; kick; stale rounds; timeout.');
if(!process.argv[2])process.exit(0);
const base=process.argv[2];
async function api(action,data={},session,expected=200){const res=await fetch(base+'/api/game',{method:'POST',headers:{'Content-Type':'application/json',...(session?{Authorization:'Bearer '+session.token}:{})},body:JSON.stringify({action,...(session?{code:session.code}:{}),...data})});const json=await res.json();assert.equal(res.status,expected,JSON.stringify(json));return json;}
async function get(session,expected=200){const res=await fetch(base+'/api/game?code='+session.code,{headers:{Authorization:'Bearer '+session.token}});const json=await res.json();assert.equal(res.status,expected,JSON.stringify(json));return json;}
const created=await api('create',{name:'Teszt házigazda'});const h={code:created.state.code,token:created.token};assert.match(h.code,/^\d{6}$/);
const join=await Promise.all([api('join',{code:h.code,name:'Teszt Anna'}),api('join',{code:h.code,name:'Teszt Bálint'})]);
const a={code:h.code,token:join[0].token},b={code:h.code,token:join[1].token};const ai=join[0].state.you,bi=join[1].state.you;
assert.equal((await get(h)).players.length,3);await api('start',{},a,403);await api('settings',{seconds:60},h);
let started=await api('start',{},h);const rr=started.state.round;assert.equal(rr.topics.length,7);assert.equal(new Set(rr.topics).size,7);
await api('join',{code:h.code,name:'Későn érkező'},undefined,400);
const ha=[rr.letter+' teszt',rr.letter+' saját','','X rossz','','',''];const aa=[rr.letter.toLowerCase()+' TESZT',rr.letter+' Anna','','','','',''];const ba=[rr.letter+' Bálint','','','','','',''];
await Promise.all([api('answers',{roundId:rr.id,answers:ha},h),api('answers',{roundId:rr.id,answers:aa},a),api('answers',{roundId:rr.id,answers:ba},b)]);
const av=await get(a);assert.equal(av.round.players.find(p=>p.id===created.state.you).answers,undefined);assert.deepEqual(av.round.players.find(p=>p.id===ai).answers,aa.map(x=>x.trim()));
await Promise.all([api('submit',{roundId:rr.id,answers:ha},h),api('submit',{roundId:rr.id,answers:aa},a),api('submit',{roundId:rr.id,answers:ba},b)]);
let reviewed=await get(h);assert.equal(reviewed.phase,'review');assert.equal(reviewed.round.players.find(p=>p.id===ai).points[0],0);assert.equal(reviewed.round.players.find(p=>p.id===bi).points[0],1);
await api('score',{roundId:rr.id,playerId:ai,value:25},a,403);await api('score',{roundId:rr.id,playerId:ai,value:25},h);assert.equal((await get(a)).players.find(p=>p.id===ai).total,25);
await api('kick',{playerId:bi},a,403);await api('kick',{playerId:bi},h);await get(b,410);
let next=await api('start',{},h);assert.equal(next.state.round.players.length,2);await api('answers',{roundId:rr.id,answers:ha},h,400);
await api('stop',{roundId:next.state.round.id},h);await api('finish',{},h);assert.equal((await get(a)).phase,'finished');await get({code:h.code,token:'forged'},401);
console.log('PASS: real D1 API room creation; simultaneous joins and autosaves; identity/host checks; hidden peer answers; 1/0 scoring; manual totals; removal; next round; stale packets; finish; forged token.');
