'use client';
import { useState, useEffect, useRef } from 'react';
import { ArrowRight, Users, Copy, Share2, Crown, X, Check, Timer, LogOut, Trophy, ChevronRight, Flag, RotateCcw } from 'lucide-react';
import { isValidAnswer, TOPICS } from '../lib/game.mjs';
import { apiUrl, homePath, inviteUrl } from '../lib/client-config';
type Session={code:string,token:string};
const EMPTY=Array(7).fill('');
function ScoreInput({value,label,max=100,onSave}:{value:number,label:string,max?:number,onSave:(n:number)=>void}) {
 const [v,setV]=useState(String(value));const focused=useRef(false);
 useEffect(()=>{if(!focused.current)setV(String(value));},[value]);
 return <input className="score-input" type="number" inputMode="numeric" min="0" max={max} step="1" aria-label={label} value={v} onFocus={()=>focused.current=true} onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}} onBlur={()=>{focused.current=false;const n=Number(v);if(v!==''&&Number.isInteger(n)&&n>=0&&n<=max&&n!==value)onSave(n);else setV(String(value));}}/>;
}
export default function Game(){
 const [name,setName]=useState(''),[code,setCode]=useState(''),[mode,setMode]=useState('create'),[session,setSession]=useState<Session|null>(null),[state,setState]=useState<any>(null),[answers,setAnswers]=useState<string[]>(EMPTY),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[network,setNetwork]=useState(''),[saved,setSaved]=useState(true),[clock,setClock]=useState(Date.now()),[rules,setRules]=useState(false),[kick,setKick]=useState<any>(null),[exitAction,setExitAction]=useState<'leave'|'finish'|null>(null),[exitError,setExitError]=useState('');
 const live=useRef<any>(null),creds=useRef<Session|null>(null),draft=useRef<string[]>(EMPTY),timer=useRef<ReturnType<typeof setTimeout>|null>(null),queue=useRef<Promise<any>>(Promise.resolve()),offset=useRef(0),mounted=useRef(false),version=useRef(0),exitTrigger=useRef<HTMLButtonElement|null>(null),exitPending=useRef(false);
 function toast(s:string){setMessage(s);}
 function consume(s:any){
  offset.current=s.serverNow-Date.now();
  if(s.round?.id!==live.current?.round?.id){if(timer.current)clearTimeout(timer.current);let a=s.round?.players.find((p:any)=>p.id===s.you)?.answers||EMPTY;try{const stored=JSON.parse(sessionStorage.getItem('ov-draft-'+s.round?.id)||'null');if(stored&&s.phase==='playing')a=stored;}catch{} draft.current=a;setAnswers(a);setSaved(true);}
  const changed=s.phase!==live.current?.phase||s.round?.id!==live.current?.round?.id;
  live.current=s;setState(s);setNetwork('');
  if(changed)requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'auto'}));
 }
 function clear(){setExitAction(null);setKick(null);if(timer.current)clearTimeout(timer.current);version.current++;creds.current=null;setSession(null);live.current=null;setState(null);sessionStorage.removeItem('ov-session');}
 async function refresh(){const c=creds.current;if(!c)return;const epoch=version.current;try{const res=await fetch(apiUrl()+'?code='+c.code,{headers:{Authorization:'Bearer '+c.token},cache:'no-store'});const data:any=await res.json();if(epoch!==version.current)return;if(!res.ok){if([401,404,410].includes(res.status)){clear();toast(data.error);}else setNetwork(data.error);return;}consume(data);}catch{if(epoch===version.current)setNetwork('A kapcsolat megszakadt. Újracsatlakozás…');}}
 function send(action:string,extra:any={}){const c=creds.current;++version.current;const task=queue.current.catch(()=>{}).then(async()=>{if(!c)throw new Error('Lépj be a szobába.');const res=await fetch(apiUrl(),{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+c.token},body:JSON.stringify({action,code:c.code,...extra})});const data:any=await res.json();if(!res.ok){if(res.status===410&&creds.current?.token===c.token)clear();throw new Error(data.error);}if(creds.current?.token===c.token){version.current++;consume(data.state);}return data;});queue.current=task;return task;}
 async function command(action:string,extra:any={},onError?:(error:string)=>void){setBusy(true);setMessage('');try{await send(action,extra);return true;}catch(e:any){const error=e.message||'Nem sikerült menteni.';toast(error);onError?.(error);await refresh();return false;}finally{setBusy(false);}}
 useEffect(()=>{mounted.current=true;try{const q=new URLSearchParams(location.search).get('szoba');if(q&&/^\d{6}$/.test(q)){setCode(q);setMode('join');}const old=JSON.parse(sessionStorage.getItem('ov-session')||'null');if(old&&(!q||q===old.code)){creds.current=old;setSession(old);refresh();}setName(sessionStorage.getItem('ov-name')||'');}catch{}return()=>{mounted.current=false;if(timer.current)clearTimeout(timer.current);};},[]);
 useEffect(()=>{if(!session)return;let fetching=false;const interval=setInterval(async()=>{if(fetching)return;fetching=true;await refresh();fetching=false;},1500);const tick=setInterval(()=>setClock(Date.now()+offset.current),250);return()=>{clearInterval(interval);clearInterval(tick);};},[session?.token]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),6000);return()=>clearTimeout(t);},[message]);
 async function enter(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const res=await fetch(apiUrl(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,name,code})});const data:any=await res.json();if(!res.ok)throw new Error(data.error);const c={code:data.state.code,token:data.token};creds.current=c;setSession(c);sessionStorage.setItem('ov-session',JSON.stringify(c));sessionStorage.setItem('ov-name',name);consume(data.state);history.replaceState(null,'',homePath()+'?szoba='+c.code);}catch(e:any){toast(e.message||'Nem sikerült csatlakozni. Próbáld újra.');}finally{setBusy(false);}}
 function edit(i:number,value:string){const a=[...draft.current];a[i]=value;draft.current=a;setAnswers(a);setSaved(false);sessionStorage.setItem('ov-draft-'+state.round.id,JSON.stringify(a));if(timer.current)clearTimeout(timer.current);const roundId=state.round.id;timer.current=setTimeout(async()=>{try{await send('answers',{roundId,answers:a});if(draft.current===a)setSaved(true);}catch{if(live.current?.phase==='playing')setNetwork('A válaszok mentése nem sikerült. A beküldéskor újrapróbáljuk.');}},450);}
 async function end(action:string){if(timer.current)clearTimeout(timer.current);if(action==='stop'&&!own?.submitted){try{await send('answers',{roundId:round.id,answers:draft.current});}catch{}}await command(action,{roundId:round.id,answers:draft.current});}
 async function share(){const url=inviteUrl(state.code);try{if(navigator.share)await navigator.share({title:'Ország–Város • Darkroom',text:'Gyere a szobába! Kód: '+state.code,url});else{await navigator.clipboard.writeText(url);toast('Meghívólink kimásolva!');}}catch(e:any){if(e.name!=='AbortError')toast('Meghívólink: '+url);}}
 function openExit(action:'leave'|'finish',trigger:HTMLButtonElement){
  if(busy)return;
  exitTrigger.current=trigger;setExitError('');setExitAction(action);
 }
 async function confirmExit(){
  if(!exitAction||exitPending.current)return;
  const action=exitAction;exitPending.current=true;setExitError('');
  try{
   if(await command(action,{},setExitError)){
    setExitAction(null);
    if(action==='leave'){clear();history.replaceState(null,'',homePath());}
   }
  }finally{exitPending.current=false;}
 }
 useEffect(()=>{
  if(exitAction||!exitTrigger.current)return;
  const trigger=exitTrigger.current;exitTrigger.current=null;
  if(trigger.isConnected)trigger.focus();
  else if(!creds.current)document.getElementById('nickname')?.focus();
 },[exitAction]);
 useEffect(()=>{
  if(!rules&&!kick&&!exitAction)return;
  const previousOverflow=document.body.style.overflow;
  document.body.style.overflow='hidden';
  const handle=(event:KeyboardEvent)=>{
   if(event.key==='Escape'){if(exitPending.current)return;setRules(false);setKick(null);setExitAction(null);return;}
   if(event.key!=='Tab')return;
   const controls=Array.from(document.querySelectorAll<HTMLElement>('.modal button:not(:disabled), .modal input, .modal a[href]'));
   if(!controls.length)return;
   const first=controls[0],last=controls[controls.length-1];
   if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}
   else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}
  };
  document.addEventListener('keydown',handle);
  return()=>{document.body.style.overflow=previousOverflow;document.removeEventListener('keydown',handle);};
 },[rules,kick,exitAction]);
 const host=state?.host===state?.you,round=state?.round,own=round?.players.find((p:any)=>p.id===state.you),remaining=round?Math.max(0,Math.ceil((round.deadline-clock)/1000)):0,filled=answers.filter(x=>x.trim()).length,ranking=state?[...state.players].sort((a:any,b:any)=>b.total-a.total):[];
 const leader=ranking[0],tied=leader?ranking.filter((p:any)=>p.total===leader.total):[];
 return <main className="app">
  <header className="topbar"><a className="brand" href={homePath()} onClick={e=>{if(session)e.preventDefault();}} aria-label="Ország–Város kezdőoldal"><span className="brand-tile">O<span>V</span></span><span>ORSZÁG–VÁROS<small>DARKROOM</small></span></a><div className="top-actions"><button className="text-button" onClick={()=>setRules(true)}>Játékszabály</button><span className="badge adult">18+</span></div></header>
  {message&&<div className="toast" role="status">{message}<button aria-label="Üzenet bezárása" onClick={()=>setMessage('')}><X size={17}/></button></div>}
  {network&&<div className="network" role="status">{network}<button onClick={refresh}>Újrapróbálás</button></div>}
  {!state?<div className="start-layout"><section className="intro"><h1>Ország,<br/>Város<em>Eredeti, kicsit másképp!</em></h1><div className="floating-letter" aria-hidden="true"><span>?</span></div></section>
   <section className="entry panel"><div className="panel-heading"><span className="mini-icon"><Users size={23}/></span><div><h2>Gyűljön össze a társaság.</h2><p>Telefon elő, becenév be.</p></div></div><div className="tabs"><button className={mode==='create'?'selected':''} onClick={()=>setMode('create')}>Új szoba</button><button className={mode==='join'?'selected':''} onClick={()=>setMode('join')}>Csatlakozás</button></div><form onSubmit={enter}><label htmlFor="nickname">A beceneved</label><input id="nickname" required maxLength={24} autoComplete="nickname" placeholder="Így hívnak majd a játékban" value={name} onChange={e=>setName(e.target.value)}/>{mode==='join'&&<><label htmlFor="roomcode">Hatjegyű szobakód</label><input className="code-input" id="roomcode" required pattern="[0-9]{6}" inputMode="numeric" autoComplete="off" maxLength={6} placeholder="000000" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></>}<button className="primary entry-submit" disabled={busy||!!session}>{busy||session?'Kapcsolódás…':mode==='create'?'Szoba létrehozása':'Belépek a szobába'}<ArrowRight size={20}/></button></form><p className="entry-note">{mode==='create'?'Te leszel a házigazda. A kódot küldd el a többieknek.':'A kódot a házigazdától kapod. Mindenki a saját készülékén játszik.'}</p>{session&&<button className="text-button" onClick={clear}>Vissza a belépéshez</button>}</section>
  </div>:<>
   <div className="room-bar"><span className="badge">{state.phase==='lobby'?'VÁRÓSZOBA':state.phase==='finished'?'VÉGEREDMÉNY':`${round?.number}. KÖR`}</span><div className="room-code"><span>SZOBAKÓD</span><button onClick={async()=>{try{await navigator.clipboard.writeText(state.code);toast('Szobakód kimásolva!');}catch{toast('Szobakód: '+state.code);}}} aria-label="Szobakód másolása">{state.code}<Copy size={17}/></button></div><button className="secondary share-button" onClick={share}><Share2 size={17}/> Meghívás</button>{!host&&<button className="icon-button" aria-label="Kilépés a szobából" disabled={busy} onClick={e=>openExit('leave',e.currentTarget)}><LogOut size={20}/></button>}</div>
   <div className="game-layout"><section className="game-main">
    {state.phase==='lobby'&&<div className="lobby panel"><div className="eyebrow">MÁR CSAK A TÁRSASÁG HIÁNYZIK</div><h1>Készen álltok<br/>a <em>következő betűre?</em></h1><p>Oszd meg a <b>{state.code}</b> kódot vagy a meghívólinket. Minden körben 7 témát sorsolunk a {TOPICS.length}-ból.</p><div className="lobby-letter" aria-hidden="true">?<span>7 TÉMA · 1 BETŰ</span></div><div className="setting"><label htmlFor="duration"><Timer size={18}/> Ennyi időtök lesz egy körre</label><select id="duration" value={state.seconds} disabled={!host||busy} onChange={e=>command('settings',{seconds:Number(e.target.value)})}><option value="60">1 perc</option><option value="90">1,5 perc</option><option value="120">2 perc</option><option value="180">3 perc</option></select></div>{host?<button className="primary" disabled={busy} onClick={()=>command('start')}>Induljon az első kör <ArrowRight size={21}/></button>:<div className="waiting">A házigazda indítja a játékot.</div>}</div>}
    {state.phase==='playing'&&<>
     <div className="round-banner"><div className="letter-tile" key={round.id}>{round.letter}</div><div className="round-info"><div className="eyebrow">EZZEL A BETŰVEL KEZDŐDJÖN</div><h1>Mi jut eszedbe?</h1><span>{filled}/7 válasz kitöltve</span></div><div className={'countdown '+(remaining<=15?'urgent':'')}><Timer size={18}/><b>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</b><span>maradt</span></div></div>
     <form onSubmit={e=>{e.preventDefault();end('submit');}} className="answer-form"><div className="answer-grid">{round.topics.map((t:string,i:number)=>{const ok=isValidAnswer(answers[i],round.letter);return <label className={'answer-card '+(ok?'filled':'')} key={round.id+t} style={{animationDelay:`${i*45}ms`}}><span className="answer-label"><span className="category-number">0{i+1}</span><span>{t}</span>{ok&&<Check size={17}/>}</span><input aria-label={t} disabled={own?.submitted||remaining===0} maxLength={100} enterKeyHint={i===6?'done':'next'} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing){e.preventDefault();const fields=Array.from(document.querySelectorAll<HTMLInputElement>('.answer-card input'));if(fields[i+1])fields[i+1].focus();else document.querySelector<HTMLButtonElement>('.submit-bar button')?.focus();}}} autoComplete="off" placeholder={`${round.letter}… (legalább 3 betű)`} value={answers[i]} onChange={e=>edit(i,e.target.value)}/></label>;})}</div><div className="submit-bar"><span className="save-status">{own?.submitted?<><Check size={16}/> Beküldve. Várjuk a többieket.</>:saved?'Válaszok mentve':'Válaszok mentése…'}</span><button className="primary" disabled={busy||own?.submitted||remaining===0} type="submit">{own?.submitted?'Kész vagyok':'Kész vagyok, beküldöm'}<Check size={19}/></button></div></form>{host&&<button className="text-button stop-button" disabled={busy} onClick={()=>end('stop')}><Flag size={16}/> Kör lezárása mindenkinek</button>}
    </>}
    {state.phase==='review'&&<><div className="section-heading"><div><div className="eyebrow">{round.letter} BETŰ · {round.number}. KÖR</div><h1>Jöhetnek a válaszok.</h1><p>{host?'Beszéljétek át! A pontmezőket átírhatod; Enterrel vagy kilépéssel mentjük.':'Beszéljétek át a válaszokat. A házigazda javíthatja a pontokat.'}</p></div><span className="round-score-icon"><Check size={32}/></span></div><div className="review-categories">{round.topics.map((t:string,i:number)=><section className="review-category panel" key={t}><h2><span className="category-number">0{i+1}</span>{t}</h2>{round.players.map((p:any)=><div className="review-row" key={p.id}><span className="review-name">{p.name}{p.id===state.you&&<small> TE</small>}</span><span className={'review-answer '+(!p.answers[i]?'empty':'')}>{p.answers[i]||'Nincs válasz'}</span>{host?<ScoreInput label={`${p.name} pontja: ${t}`} value={p.points[i]} onSave={n=>command('score',{roundId:round.id,playerId:p.id,index:i,value:n})}/>:<span className={'point-pill '+(p.points[i]===1?'positive':'')}>{p.points[i]}</span>}</div>)}</section>)}</div><div className="review-actions">{host?<><button className="primary" disabled={busy||state.roundCount>=50} onClick={()=>command('start')}>Következő kör <ChevronRight size={21}/></button><button className="secondary" disabled={busy} onClick={e=>openExit('finish',e.currentTarget)}>Játék befejezése</button></>:<div className="waiting">A házigazda indítja a következő kört.</div>}</div></>}
    {state.phase==='finished'&&<div className="final panel"><span className="winner-icon"><Trophy size={52}/></span><div className="eyebrow">{state.roundCount} KÖR UTÁN</div><h1>{tied.length>1?'Döntetlen!':`${leader?.name||'A társaság'} nyert!`}</h1><p>{tied.map((p:any)=>p.name).join(' · ')}</p><div className="winner-points">{leader?.total||0}<span>PONT</span></div><a className="primary" href={homePath()} onClick={clear}><RotateCcw size={19}/> Új társaság, új játék</a></div>}
   </section>
   <aside className="players panel"><div className="players-title"><h2>{state.phase==='lobby'?'A társaság':'Állás'}</h2><span><Users size={16}/>{state.players.length}/20</span></div><div className="player-list">{ranking.map((p:any,i:number)=><div className="player" key={p.id}><span className={'avatar color-'+i%5}>{p.name.slice(0,1).toLocaleUpperCase('hu')}</span><div className="player-name"><strong>{p.name}</strong><small>{p.id===state.host?<><Crown size={12}/> Házigazda</>:p.id===state.you?'Te':state.phase==='playing'?(round.players.find((x:any)=>x.id===p.id)?.submitted?'Beküldve':'Még gondolkodik…'):`${i+1}. hely`}</small></div>{state.phase!=='lobby'&&(host&&state.phase==='review'&&round.players.some((x:any)=>x.id===p.id)?<ScoreInput label={`${p.name} összpontszáma`} max={10000} value={p.total} onSave={n=>command('score',{roundId:round.id,playerId:p.id,value:n})}/>:<span className="total-points">{p.total}<small>pont</small></span>)}{host&&p.id!==state.host&&state.phase!=='finished'&&<button className="kick-button" aria-label={`${p.name} eltávolítása`} title="Eltávolítás" onClick={()=>setKick(p)}><X size={16}/></button>}</div>)}</div>{host&&state.phase==='review'&&<p className="side-note">Az összpontot is átírhatod.<br/>Minden játékosnál külön mentjük.</p>}<div className="scoring"><span>PONTOZÁS</span><div><b>1</b> egyedi válasz</div><div><b>0</b> azonos válasz</div><div><b>0</b> üres válasz</div></div>{state.phase==='lobby'&&state.players.length===1&&<p className="side-note">Még csak te vagy itt.<br/>Hívd meg a többieket!</p>}</aside>
   </div>
  </>}
  <footer><span>ORSZÁG–VÁROS / DARKROOM</span></footer>
  {rules&&<div className="modal-backdrop" onClick={()=>setRules(false)}><section className="modal panel" role="dialog" aria-modal="true" aria-labelledby="rules-title" onClick={e=>e.stopPropagation()}><button autoFocus className="modal-close icon-button" aria-label="Bezárás" onClick={()=>setRules(false)}><X/></button><div className="eyebrow">JÁTÉKSZABÁLY</div><h2 id="rules-title">Egy betű, hét válasz.</h2><ol><li>A házigazda létrehoz egy szobát. A többiek becenévvel és a hatjegyű kóddal belépnek.</li><li>Minden körben új betűt és 7 különböző témát sorsolunk. A betűk egy teljes sorozaton belül nem ismétlődnek.</li><li>Írjatok a kisorsolt betűvel kezdődő, legalább 3 betűből álló válaszokat! A szóközök, számok és írásjelek nem számítanak betűnek. Az ékezetpárok egyenértékűek: A/Á, E/É, I/Í, O/Ó/Ö/Ő, U/Ú/Ü/Ű.</li><li>A beküldés lezárja a saját válaszaidat. Ha mindenki kész, az idő lejár, vagy a házigazda lezárja, jön a pontozás.</li><li>Egyedi válasz: 1 pont. Azonos válasz: 0 pont. Üres, 3 betűnél rövidebb vagy rossz kezdőbetűjű válasz: 0 pont. Kis- és nagybetű, ékezet és felesleges szóköz nem számít eltérésnek.</li><li>A témába illő válaszokat közösen bíráljátok el. A házigazda a kör végén válaszonként vagy összpontban javíthat, és játékost is eltávolíthat.</li></ol><p>A szoba 24 óráig él. Új játékos két kör között csatlakozhat. Újratöltéskor ugyanabban a böngészőfülben visszatérhetsz.</p><button className="primary" onClick={()=>setRules(false)}>Értem, játsszunk <ArrowRight size={18}/></button></section></div>}
  {exitAction&&<div className="modal-backdrop" onClick={()=>{if(!exitPending.current)setExitAction(null);}}><section className="modal panel" role="dialog" aria-modal="true" aria-labelledby="exit-title" aria-describedby="exit-description" aria-busy={busy} onClick={e=>e.stopPropagation()}><h2 id="exit-title">{exitAction==='leave'?'Kilépsz a szobából?':'Befejezed a játékot?'}</h2><p id="exit-description">{exitAction==='leave'?'Visszakerülsz a kezdőlapra. A többiek a szobában maradnak.':'Minden játékosnál lezárul a játék, és megjelenik a végeredmény.'}</p>{exitError&&<p className="exit-error" role="alert">{exitError}</p>}<div className="review-actions"><button className="secondary" autoFocus disabled={busy} onClick={()=>setExitAction(null)}>Mégsem</button><button className="primary" disabled={busy} onClick={confirmExit}>{busy?'Egy pillanat…':exitAction==='leave'?'Kilépés':'Befejezés'}<LogOut size={18}/></button></div></section></div>}
  {kick&&<div className="modal-backdrop"><section className="modal panel" role="dialog" aria-modal="true" aria-labelledby="kick-title"><h2 id="kick-title">Eltávolítod {kick.name} játékost?</h2><p>Nem vesz részt a következő körökben. Az eddigi válaszai és pontjai megmaradnak.</p><div className="review-actions"><button className="secondary" autoFocus onClick={()=>setKick(null)}>Mégsem</button><button className="primary" disabled={busy} onClick={async()=>{if(await command('kick',{playerId:kick.id}))setKick(null);}}>Eltávolítás <X size={18}/></button></div></section></div>}
 </main>;
}
